### ISSUE TITLE
How to separate private from public images

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4jrb-paperclip#1]
Hi Chris,
I integrated your gem in my application.

It produces a long directory tree under public/system, which hide (obfuscate) the real name of the image file.

But the tree is still public. 

I need to have a couple of destination, one public and one private, accessible only thru a controller.
Have you got any suggestion about this kind of structure? I saw on the internet that it is a wide shared question without a clear clean solution ....

**Comment by chrislgrigg** [comment]
Afraid not. I've never actually used Paperclip beyond figuring out how to make it work with the newest version of Neo4j.rb.
