### ISSUE TITLE
Can't get it to work with current versions (Rails 5, Neo4jrb 8)

### ISSUE THREAD

**Issue by Joshfindit** [neo4jrb/neo4jrb-paperclip#5]
### First issue

 `NameError: uninitialized constant Artefact::Neo4jrb`

#### Artefact model
```
class Artefact 
  include Neo4j::ActiveNode
  include Neo4jrb::Paperclip

  property :name, type: String
  property :description, type: String

  has_neo4jrb_attached_file :ingestedFile
  do_not_validate_attachment_file_type :ingestedFile

  has_many :both, :artefacts, type: :REFERS_TO, model_class: :Artefact
  has_many :out, :identities_with_permission, type: :PERMISSION_TO, model_class: :Identity 
end
```

### Response
 Fork, rename `Neo4jrb` to `Neo4j` (https://github.com/Joshfindit/neo4jrb-paperclip)

### Result
Properties added to Neo4j the nodes:
```
ingestedFile_content_type: nil, ingestedFile_file_name: nil, ingestedFile_file_size: nil, ingestedFile_updated_at: nil
```

### Second issue
`Artefact.first.ingestedFile = File.open("file.txt")` seems to succeed, but does not attach the file AND gives no errors.

```
 CYPHER 
  MATCH (n:`Artefact`)
  RETURN n
  ORDER BY n.uuid
  LIMIT {limit_1} | {:limit_1=>1}
Command :: file -b --mime 'file.txt'
Command :: file -b --mime '/tmp/4f39afe40a56a1a6385b6d438773f95720170114-1251-1hspec9.txt'
=> #<File:file.txt>
irb(main):064:0> Artefact.first.ingestedFile.url                         
 CYPHER 
  MATCH (n:`Artefact`)
  RETURN n
  ORDER BY n.uuid
  LIMIT {limit_1} | {:limit_1=>1}
=> "/ingestedfilemetadata/original/missing.png"
rb(main):071:0> Artefact.first.ingestedFile.original_filename
 CYPHER 
  MATCH (n:`Artefact`)
  RETURN n
  ORDER BY n.uuid
  LIMIT {limit_1} | {:limit_1=>1}
=> nil
```

**Comment by cheerfulstoic** [comment]
Talked with @Joshfindit Slack.  Best guess so far is that 5.0.0 of `paperclip` might have broken things, and/or maybe I've been working with version 1.x of `aws-sdk`

**Comment by Joshfindit** [comment]
Bullet-point list from the discussion in the Slack channel (thanks @cheerfulstoic - these have it working for my app):

- We didn’t use camelCase, so you might try snake_case.
- This is also in our `config/application.rb` (for S3):

```    config.paperclip_defaults = {
      storage: :s3,
      s3_credentials: {
        bucket: ENV['S3_BUCKET_NAME']
      },
      s3_permissions: :private,
      s3_server_side_encryption: :aes256,
      url: ':s3_domain_url',
      path: DEFAULT_FILE_PATH
    }
```
- `require 'paperclip/railtie'` at the top of the `config/application.rb`
- There’s also a `require 'neo4jrb_paperclip'` at the top of our paperclip models
- `Gemfile.lock`
  - `neo4jrb-paperclip (0.0.3)`
  - `paperclip (4.3.7)`(not using >5.0.0 of `paperclip`)
- We’re also using version 1.66.0 of `aws-sdk` and 5.0 dropped support for 1.x.
